"use strict";
function __export(m) {
    for (var p in m) if (!exports.hasOwnProperty(p)) exports[p] = m[p];
}
Object.defineProperty(exports, "__esModule", { value: true });
__export(require("./categoryControllerService.service"));
var categoryControllerService_service_1 = require("./categoryControllerService.service");
__export(require("./companyControllerService.service"));
var companyControllerService_service_1 = require("./companyControllerService.service");
__export(require("./companyTypeControllerService.service"));
var companyTypeControllerService_service_1 = require("./companyTypeControllerService.service");
__export(require("./groupControllerService.service"));
var groupControllerService_service_1 = require("./groupControllerService.service");
__export(require("./inventoryControllerService.service"));
var inventoryControllerService_service_1 = require("./inventoryControllerService.service");
__export(require("./moduleControllerService.service"));
var moduleControllerService_service_1 = require("./moduleControllerService.service");
__export(require("./productFeatureControllerService.service"));
var productFeatureControllerService_service_1 = require("./productFeatureControllerService.service");
__export(require("./productPromotionControllerService.service"));
var productPromotionControllerService_service_1 = require("./productPromotionControllerService.service");
__export(require("./productReviewControllerService.service"));
var productReviewControllerService_service_1 = require("./productReviewControllerService.service");
__export(require("./roleControllerService.service"));
var roleControllerService_service_1 = require("./roleControllerService.service");
__export(require("./saleControllerService.service"));
var saleControllerService_service_1 = require("./saleControllerService.service");
__export(require("./shippingControllerService.service"));
var shippingControllerService_service_1 = require("./shippingControllerService.service");
__export(require("./storeControllerService.service"));
var storeControllerService_service_1 = require("./storeControllerService.service");
__export(require("./ticketControllerService.service"));
var ticketControllerService_service_1 = require("./ticketControllerService.service");
__export(require("./typeControllerService.service"));
var typeControllerService_service_1 = require("./typeControllerService.service");
__export(require("./userControllerService.service"));
var userControllerService_service_1 = require("./userControllerService.service");
__export(require("./verificationCodeControllerService.service"));
var verificationCodeControllerService_service_1 = require("./verificationCodeControllerService.service");
__export(require("./warrantyControllerService.service"));
var warrantyControllerService_service_1 = require("./warrantyControllerService.service");
exports.APIS = [categoryControllerService_service_1.CategoryControllerServiceService, companyControllerService_service_1.CompanyControllerServiceService, companyTypeControllerService_service_1.CompanyTypeControllerServiceService, groupControllerService_service_1.GroupControllerServiceService, inventoryControllerService_service_1.InventoryControllerServiceService, moduleControllerService_service_1.ModuleControllerServiceService, productFeatureControllerService_service_1.ProductFeatureControllerServiceService, productPromotionControllerService_service_1.ProductPromotionControllerServiceService, productReviewControllerService_service_1.ProductReviewControllerServiceService, roleControllerService_service_1.RoleControllerServiceService, saleControllerService_service_1.SaleControllerServiceService, shippingControllerService_service_1.ShippingControllerServiceService, storeControllerService_service_1.StoreControllerServiceService, ticketControllerService_service_1.TicketControllerServiceService, typeControllerService_service_1.TypeControllerServiceService, userControllerService_service_1.UserControllerServiceService, verificationCodeControllerService_service_1.VerificationCodeControllerServiceService, warrantyControllerService_service_1.WarrantyControllerServiceService];
