export * from './categoryControllerService.service';
import { CategoryControllerServiceService } from './categoryControllerService.service';
export * from './companyControllerService.service';
import { CompanyControllerServiceService } from './companyControllerService.service';
export * from './companyTypeControllerService.service';
import { CompanyTypeControllerServiceService } from './companyTypeControllerService.service';
export * from './groupControllerService.service';
import { GroupControllerServiceService } from './groupControllerService.service';
export * from './inventoryControllerService.service';
import { InventoryControllerServiceService } from './inventoryControllerService.service';
export * from './moduleControllerService.service';
import { ModuleControllerServiceService } from './moduleControllerService.service';
export * from './productFeatureControllerService.service';
import { ProductFeatureControllerServiceService } from './productFeatureControllerService.service';
export * from './productPromotionControllerService.service';
import { ProductPromotionControllerServiceService } from './productPromotionControllerService.service';
export * from './roleControllerService.service';
import { RoleControllerServiceService } from './roleControllerService.service';
export * from './saleControllerService.service';
import { SaleControllerServiceService } from './saleControllerService.service';
export * from './shippingControllerService.service';
import { ShippingControllerServiceService } from './shippingControllerService.service';
export * from './storeControllerService.service';
import { StoreControllerServiceService } from './storeControllerService.service';
export * from './ticketControllerService.service';
import { TicketControllerServiceService } from './ticketControllerService.service';
export * from './typeControllerService.service';
import { TypeControllerServiceService } from './typeControllerService.service';
export * from './userControllerService.service';
import { UserControllerServiceService } from './userControllerService.service';
export * from './verificationCodeControllerService.service';
import { VerificationCodeControllerServiceService } from './verificationCodeControllerService.service';
export * from './warrantyControllerService.service';
import { WarrantyControllerServiceService } from './warrantyControllerService.service';
export const APIS = [CategoryControllerServiceService, CompanyControllerServiceService, CompanyTypeControllerServiceService, GroupControllerServiceService, InventoryControllerServiceService, ModuleControllerServiceService, ProductFeatureControllerServiceService, ProductPromotionControllerServiceService, RoleControllerServiceService, SaleControllerServiceService, ShippingControllerServiceService, StoreControllerServiceService, TicketControllerServiceService, TypeControllerServiceService, UserControllerServiceService, VerificationCodeControllerServiceService, WarrantyControllerServiceService];
