/**
 * Ipoh Drum Laravel API
 * This is a swagger-generated API documentation for the project Ipoh Drum. (Only supports OpenAPI Annotations for now.)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: henry_lcz97@hotmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent, HttpParameterCodec }       from '@angular/common/http';
import { CustomHttpParameterCodec }                          from '../encoder';
import { Observable }                                        from 'rxjs';


import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';



@Injectable({
  providedIn: 'root'
})
export class SaleControllerServiceService {

    protected basePath = 'http://172.104.45.205';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();
    public encoder: HttpParameterCodec;

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (configuration) {
            this.configuration = configuration;
        }
        if (typeof this.configuration.basePath !== 'string') {
            if (typeof basePath !== 'string') {
                basePath = this.basePath;
            }
            this.configuration.basePath = basePath;
        }
        this.encoder = this.configuration.encoder || new CustomHttpParameterCodec();
    }



    private addToHttpParams(httpParams: HttpParams, value: any, key?: string): HttpParams {
        if (typeof value === "object") {
            httpParams = this.addToHttpParamsRecursive(httpParams, value);
        } else {
            httpParams = this.addToHttpParamsRecursive(httpParams, value, key);
        }
        return httpParams;
    }

    private addToHttpParamsRecursive(httpParams: HttpParams, value: any, key?: string): HttpParams {
        if (typeof value === "object") {
            if (Array.isArray(value)) {
                (value as any[]).forEach( elem => httpParams = this.addToHttpParamsRecursive(httpParams, elem, key));
            } else if (value instanceof Date) {
                if (key != null) {
                    httpParams = httpParams.append(key,
                        (value as Date).toISOString().substr(0, 10));
                } else {
                   throw Error("key may not be null if value is Date");
                }
            } else {
                Object.keys(value).forEach( k => httpParams = this.addToHttpParamsRecursive(
                    httpParams, value[k], key != null ? `${key}.${k}` : k));
            }
        } else if (key != null) {
            httpParams = httpParams.append(key, value);
        } else {
            throw Error("key may not be null if value is not object or array");
        }
        return httpParams;
    }

    /**
     * Creates a sale.
     * @param name Salename
     * @param storeid Store ID
     * @param sku Sku
     * @param cost Product Cost
     * @param price Product Selling Price
     * @param stock Stock Qty
     * @param onsale On Sale
     * @param code Code
     * @param desc Product Description
     * @param disc Product Discount
     * @param promoprice Promotion Price
     * @param promostartdate Promotion Start Date
     * @param promoenddate Promotion End Date
     * @param warrantyperiod Warranty Period
     * @param stockthreshold Stock Threshold
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public createSale(name: string, storeid: number, sku: string, cost: number, price: number, stock: number, onsale: number, code?: string, desc?: string, disc?: number, promoprice?: string, promostartdate?: string, promoenddate?: string, warrantyperiod?: number, stockthreshold?: number, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: undefined}): Observable<any>;
    public createSale(name: string, storeid: number, sku: string, cost: number, price: number, stock: number, onsale: number, code?: string, desc?: string, disc?: number, promoprice?: string, promostartdate?: string, promoenddate?: string, warrantyperiod?: number, stockthreshold?: number, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: undefined}): Observable<HttpResponse<any>>;
    public createSale(name: string, storeid: number, sku: string, cost: number, price: number, stock: number, onsale: number, code?: string, desc?: string, disc?: number, promoprice?: string, promostartdate?: string, promoenddate?: string, warrantyperiod?: number, stockthreshold?: number, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: undefined}): Observable<HttpEvent<any>>;
    public createSale(name: string, storeid: number, sku: string, cost: number, price: number, stock: number, onsale: number, code?: string, desc?: string, disc?: number, promoprice?: string, promostartdate?: string, promoenddate?: string, warrantyperiod?: number, stockthreshold?: number, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: undefined}): Observable<any> {
        if (name === null || name === undefined) {
            throw new Error('Required parameter name was null or undefined when calling createSale.');
        }
        if (storeid === null || storeid === undefined) {
            throw new Error('Required parameter storeid was null or undefined when calling createSale.');
        }
        if (sku === null || sku === undefined) {
            throw new Error('Required parameter sku was null or undefined when calling createSale.');
        }
        if (cost === null || cost === undefined) {
            throw new Error('Required parameter cost was null or undefined when calling createSale.');
        }
        if (price === null || price === undefined) {
            throw new Error('Required parameter price was null or undefined when calling createSale.');
        }
        if (stock === null || stock === undefined) {
            throw new Error('Required parameter stock was null or undefined when calling createSale.');
        }
        if (onsale === null || onsale === undefined) {
            throw new Error('Required parameter onsale was null or undefined when calling createSale.');
        }

        let queryParameters = new HttpParams({encoder: this.encoder});
        if (name !== undefined && name !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>name, 'name');
        }
        if (storeid !== undefined && storeid !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>storeid, 'storeid');
        }
        if (code !== undefined && code !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>code, 'code');
        }
        if (sku !== undefined && sku !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>sku, 'sku');
        }
        if (desc !== undefined && desc !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>desc, 'desc');
        }
        if (cost !== undefined && cost !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>cost, 'cost');
        }
        if (price !== undefined && price !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>price, 'price');
        }
        if (disc !== undefined && disc !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>disc, 'disc');
        }
        if (promoprice !== undefined && promoprice !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>promoprice, 'promoprice');
        }
        if (promostartdate !== undefined && promostartdate !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>promostartdate, 'promostartdate');
        }
        if (promoenddate !== undefined && promoenddate !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>promoenddate, 'promoenddate');
        }
        if (stock !== undefined && stock !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>stock, 'stock');
        }
        if (warrantyperiod !== undefined && warrantyperiod !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>warrantyperiod, 'warrantyperiod');
        }
        if (stockthreshold !== undefined && stockthreshold !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>stockthreshold, 'stockthreshold');
        }
        if (onsale !== undefined && onsale !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>onsale, 'onsale');
        }

        let headers = this.defaultHeaders;

        let httpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (httpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
            ];
            httpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        let responseType: 'text' | 'json' = 'json';
        if(httpHeaderAcceptSelected && httpHeaderAcceptSelected.startsWith('text')) {
            responseType = 'text';
        }

        return this.httpClient.post<any>(`${this.configuration.basePath}/api/sale`,
            null,
            {
                params: queryParameters,
                responseType: <any>responseType,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Set sale\&#39;s \&#39;status\&#39; to 0.
     * @param uid Sale ID, NOT \&#39;ID\&#39;.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public deleteSaleByUid(uid: string, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: undefined}): Observable<any>;
    public deleteSaleByUid(uid: string, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: undefined}): Observable<HttpResponse<any>>;
    public deleteSaleByUid(uid: string, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: undefined}): Observable<HttpEvent<any>>;
    public deleteSaleByUid(uid: string, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: undefined}): Observable<any> {
        if (uid === null || uid === undefined) {
            throw new Error('Required parameter uid was null or undefined when calling deleteSaleByUid.');
        }

        let headers = this.defaultHeaders;

        let httpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (httpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
            ];
            httpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        let responseType: 'text' | 'json' = 'json';
        if(httpHeaderAcceptSelected && httpHeaderAcceptSelected.startsWith('text')) {
            responseType = 'text';
        }

        return this.httpClient.delete<any>(`${this.configuration.basePath}/api/sale/${encodeURIComponent(String(uid))}`,
            {
                responseType: <any>responseType,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Filter list of sales
     * Returns list of filtered sales
     * @param page_number Page number
     * @param page_size Page size
     * @param keyword Keyword for filter
     * @param fromdate From Date for filter
     * @param todate To string for filter
     * @param status status for filter
     * @param onsale onsale for filter
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public filterSaleList(page_number?: number, page_size?: number, keyword?: string, fromdate?: string, todate?: string, status?: string, onsale?: string, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: undefined}): Observable<any>;
    public filterSaleList(page_number?: number, page_size?: number, keyword?: string, fromdate?: string, todate?: string, status?: string, onsale?: string, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: undefined}): Observable<HttpResponse<any>>;
    public filterSaleList(page_number?: number, page_size?: number, keyword?: string, fromdate?: string, todate?: string, status?: string, onsale?: string, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: undefined}): Observable<HttpEvent<any>>;
    public filterSaleList(page_number?: number, page_size?: number, keyword?: string, fromdate?: string, todate?: string, status?: string, onsale?: string, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: undefined}): Observable<any> {

        let queryParameters = new HttpParams({encoder: this.encoder});
        if (page_number !== undefined && page_number !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>page_number, 'pageNumber');
        }
        if (page_size !== undefined && page_size !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>page_size, 'pageSize');
        }
        if (keyword !== undefined && keyword !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>keyword, 'keyword');
        }
        if (fromdate !== undefined && fromdate !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>fromdate, 'fromdate');
        }
        if (todate !== undefined && todate !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>todate, 'todate');
        }
        if (status !== undefined && status !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>status, 'status');
        }
        if (onsale !== undefined && onsale !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>onsale, 'onsale');
        }

        let headers = this.defaultHeaders;

        let httpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (httpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
            ];
            httpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        let responseType: 'text' | 'json' = 'json';
        if(httpHeaderAcceptSelected && httpHeaderAcceptSelected.startsWith('text')) {
            responseType = 'text';
        }

        return this.httpClient.get<any>(`${this.configuration.basePath}/api/filter/sale`,
            {
                params: queryParameters,
                responseType: <any>responseType,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Retrieves sale by Uid.
     * @param uid Sale_ID, NOT \&#39;ID\&#39;.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getSaleByUid(uid: string, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: undefined}): Observable<any>;
    public getSaleByUid(uid: string, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: undefined}): Observable<HttpResponse<any>>;
    public getSaleByUid(uid: string, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: undefined}): Observable<HttpEvent<any>>;
    public getSaleByUid(uid: string, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: undefined}): Observable<any> {
        if (uid === null || uid === undefined) {
            throw new Error('Required parameter uid was null or undefined when calling getSaleByUid.');
        }

        let headers = this.defaultHeaders;

        let httpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (httpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
            ];
            httpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        let responseType: 'text' | 'json' = 'json';
        if(httpHeaderAcceptSelected && httpHeaderAcceptSelected.startsWith('text')) {
            responseType = 'text';
        }

        return this.httpClient.get<any>(`${this.configuration.basePath}/api/sale/${encodeURIComponent(String(uid))}`,
            {
                responseType: <any>responseType,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get list of sales
     * Returns list of sales
     * @param page_number Page number
     * @param page_size number of pageSize
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getSales(page_number?: number, page_size?: number, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: undefined}): Observable<any>;
    public getSales(page_number?: number, page_size?: number, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: undefined}): Observable<HttpResponse<any>>;
    public getSales(page_number?: number, page_size?: number, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: undefined}): Observable<HttpEvent<any>>;
    public getSales(page_number?: number, page_size?: number, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: undefined}): Observable<any> {

        let queryParameters = new HttpParams({encoder: this.encoder});
        if (page_number !== undefined && page_number !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>page_number, 'pageNumber');
        }
        if (page_size !== undefined && page_size !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>page_size, 'pageSize');
        }

        let headers = this.defaultHeaders;

        let httpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (httpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
            ];
            httpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        let responseType: 'text' | 'json' = 'json';
        if(httpHeaderAcceptSelected && httpHeaderAcceptSelected.startsWith('text')) {
            responseType = 'text';
        }

        return this.httpClient.get<any>(`${this.configuration.basePath}/api/sale`,
            {
                params: queryParameters,
                responseType: <any>responseType,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * User Ordered Sale
     * @param page_number Page number
     * @param page_size number of pageSize
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getUserSales(page_number?: number, page_size?: number, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: undefined}): Observable<any>;
    public getUserSales(page_number?: number, page_size?: number, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: undefined}): Observable<HttpResponse<any>>;
    public getUserSales(page_number?: number, page_size?: number, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: undefined}): Observable<HttpEvent<any>>;
    public getUserSales(page_number?: number, page_size?: number, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: undefined}): Observable<any> {

        let queryParameters = new HttpParams({encoder: this.encoder});
        if (page_number !== undefined && page_number !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>page_number, 'pageNumber');
        }
        if (page_size !== undefined && page_size !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>page_size, 'pageSize');
        }

        let headers = this.defaultHeaders;

        let httpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (httpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
            ];
            httpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        let responseType: 'text' | 'json' = 'json';
        if(httpHeaderAcceptSelected && httpHeaderAcceptSelected.startsWith('text')) {
            responseType = 'text';
        }

        return this.httpClient.get<any>(`${this.configuration.basePath}/api/usersales`,
            {
                params: queryParameters,
                responseType: <any>responseType,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Update sale by Uid.
     * @param uid Sale_ID, NOT \&#39;ID\&#39;.
     * @param name Salename
     * @param storeid Store ID
     * @param userid User ID
     * @param sku totalqty
     * @param totalcost All Product Cost
     * @param totaldisc Total Discount
     * @param stock Stock Qty
     * @param stockthreshold Stock Threshold
     * @param onsale On Sale
     * @param sono Sale Order No
     * @param linetotal Line Total
     * @param disc Product Discount
     * @param promoprice Promotion Price
     * @param promostartdate Promotion Start Date
     * @param promoenddate Promotion End Date
     * @param warrantyperiod Warranty Period
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public updateSaleByUid(uid: string, name: string, storeid: number, userid: number, sku: number, totalcost: number, totaldisc: number, stock: number, stockthreshold: number, onsale: number, sono?: string, linetotal?: number, disc?: number, promoprice?: string, promostartdate?: string, promoenddate?: string, warrantyperiod?: number, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: undefined}): Observable<any>;
    public updateSaleByUid(uid: string, name: string, storeid: number, userid: number, sku: number, totalcost: number, totaldisc: number, stock: number, stockthreshold: number, onsale: number, sono?: string, linetotal?: number, disc?: number, promoprice?: string, promostartdate?: string, promoenddate?: string, warrantyperiod?: number, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: undefined}): Observable<HttpResponse<any>>;
    public updateSaleByUid(uid: string, name: string, storeid: number, userid: number, sku: number, totalcost: number, totaldisc: number, stock: number, stockthreshold: number, onsale: number, sono?: string, linetotal?: number, disc?: number, promoprice?: string, promostartdate?: string, promoenddate?: string, warrantyperiod?: number, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: undefined}): Observable<HttpEvent<any>>;
    public updateSaleByUid(uid: string, name: string, storeid: number, userid: number, sku: number, totalcost: number, totaldisc: number, stock: number, stockthreshold: number, onsale: number, sono?: string, linetotal?: number, disc?: number, promoprice?: string, promostartdate?: string, promoenddate?: string, warrantyperiod?: number, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: undefined}): Observable<any> {
        if (uid === null || uid === undefined) {
            throw new Error('Required parameter uid was null or undefined when calling updateSaleByUid.');
        }
        if (name === null || name === undefined) {
            throw new Error('Required parameter name was null or undefined when calling updateSaleByUid.');
        }
        if (storeid === null || storeid === undefined) {
            throw new Error('Required parameter storeid was null or undefined when calling updateSaleByUid.');
        }
        if (userid === null || userid === undefined) {
            throw new Error('Required parameter userid was null or undefined when calling updateSaleByUid.');
        }
        if (sku === null || sku === undefined) {
            throw new Error('Required parameter sku was null or undefined when calling updateSaleByUid.');
        }
        if (totalcost === null || totalcost === undefined) {
            throw new Error('Required parameter totalcost was null or undefined when calling updateSaleByUid.');
        }
        if (totaldisc === null || totaldisc === undefined) {
            throw new Error('Required parameter totaldisc was null or undefined when calling updateSaleByUid.');
        }
        if (stock === null || stock === undefined) {
            throw new Error('Required parameter stock was null or undefined when calling updateSaleByUid.');
        }
        if (stockthreshold === null || stockthreshold === undefined) {
            throw new Error('Required parameter stockthreshold was null or undefined when calling updateSaleByUid.');
        }
        if (onsale === null || onsale === undefined) {
            throw new Error('Required parameter onsale was null or undefined when calling updateSaleByUid.');
        }

        let queryParameters = new HttpParams({encoder: this.encoder});
        if (name !== undefined && name !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>name, 'name');
        }
        if (storeid !== undefined && storeid !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>storeid, 'storeid');
        }
        if (userid !== undefined && userid !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>userid, 'userid');
        }
        if (sono !== undefined && sono !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>sono, 'sono');
        }
        if (sku !== undefined && sku !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>sku, 'sku');
        }
        if (linetotal !== undefined && linetotal !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>linetotal, 'linetotal');
        }
        if (totalcost !== undefined && totalcost !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>totalcost, 'totalcost');
        }
        if (totaldisc !== undefined && totaldisc !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>totaldisc, 'totaldisc');
        }
        if (disc !== undefined && disc !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>disc, 'disc');
        }
        if (promoprice !== undefined && promoprice !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>promoprice, 'promoprice');
        }
        if (promostartdate !== undefined && promostartdate !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>promostartdate, 'promostartdate');
        }
        if (promoenddate !== undefined && promoenddate !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>promoenddate, 'promoenddate');
        }
        if (stock !== undefined && stock !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>stock, 'stock');
        }
        if (warrantyperiod !== undefined && warrantyperiod !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>warrantyperiod, 'warrantyperiod');
        }
        if (stockthreshold !== undefined && stockthreshold !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>stockthreshold, 'stockthreshold');
        }
        if (onsale !== undefined && onsale !== null) {
          queryParameters = this.addToHttpParams(queryParameters,
            <any>onsale, 'onsale');
        }

        let headers = this.defaultHeaders;

        let httpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (httpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
            ];
            httpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        let responseType: 'text' | 'json' = 'json';
        if(httpHeaderAcceptSelected && httpHeaderAcceptSelected.startsWith('text')) {
            responseType = 'text';
        }

        return this.httpClient.put<any>(`${this.configuration.basePath}/api/sale/${encodeURIComponent(String(uid))}`,
            null,
            {
                params: queryParameters,
                responseType: <any>responseType,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
