/**
 * Ipoh Drum Laravel API
 * This is a swagger-generated API documentation for the project Ipoh Drum. (Only supports OpenAPI Annotations for now.)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: henry_lcz97@hotmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Sale { 
    id?: number;
    accountId?: number;
    userId?: number;
    uid?: string;
    sono?: string;
    totalqty?: number;
    discpctg?: number;
    totalcost?: number;
    totalbfdisc?: number;
    totalbftax?: number;
    totaldisc?: number;
    grandtotal?: number;
    payment?: number;
    outstanding?: number;
    status?: string;
    lasteditBy?: string;
    remark?: string;
    docdate?: string;
    pos?: number;
    rememberToken?: string;
    createdAt?: string;
    updatedAt?: string;
}

